apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: suraj
  labels:
    project: suraj
    env: dev
    component: db
spec:
  replicas: 3
  selector:
    matchLabels:
      project: suraj
      env: dev
      component: db
  template:
    metadata:
      labels:
        project: suraj
        env: dev
        component: db
    spec:
      containers:
      - name: paayment
        image: 296062550816.dkr.ecr.us-east-1.amazonaws.com/suraj/dev/payments:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment


  
---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: suraj

spec:
  selector:
    project: suraj
    env: dev
    component: db

  ports:
  - name: payment-port
    protocol: TCP
    port: 8080
    targetPort: 8080
